---
title: "Reproducible Research Peer Assessment 1"
author: "Abhijit"
date: "Monday, January 19, 2015"
output: html_document
---
Part 1:

```{r,echo=TRUE}
d<-read.csv('activity.csv')

ad<-tapply(d$steps,d$date,sum, na.rm=TRUE)

hist(ad, main="Frequency of total steps taken each day", xlab="Total number of steps taken in a day", col = "red", ylim=c(0,30))

meansteps<-mean(ad)
print(meansteps)

mediansteps<-median(ad)
print (mediansteps)


ad2<-aggregate(steps ~ interval, d, mean, na.rm=TRUE)
plot(ad2, type="l", main="Average number of steps for each interval", xlab="5 minute intervals", ylab="Averaged No. of steps taken in interval", col="red")

ad2[ad2$steps==max(ad2$steps),]
```

Impute missing values

Strategy: Impute with mean no. of steps in that interval wherever data is NA.
```{r, echo=TRUE}
NArows=nrow(d[is.na(d$steps),])
print(NArows)

ad3<-aggregate(steps~date,d,mean, na.rm=TRUE)
d2<-d
filldata<-mean(ad2$steps)
d2$steps[d2$steps=="NA"]<-filldata
id<-tapply(d2$steps,d2$date, sum, na.rm=TRUE)
hist(id, main="Total no. of steps taken each day with imputed values",xlab="Total number of steps taken in a day", col = "red", ylim=c(0,30))

imean<-mean(id)
print(imean)

imedian<-median(id)
print(imedian)

diffmean<-imean-meansteps
print(diffmean)

diffmedian<- imedian - mediansteps
print(diffmedian)


```
Add a weekend factor to revised dataset

```{r, echo=TRUE}
d2$wend<-as.factor(ifelse(weekdays( as.POSIXlt(d2$date)) %in% c("Saturday","Sunday"), "Weekend", "Weekday")) 
d2week<-d2[d2$wend=="Weekday",]
d2weekend<-d2[d2$wend=="Weekend",]
ad4<-aggregate(d2week$steps, by=list(interval=d2week$interval), mean, na.rm=TRUE)
ad5<-aggregate(d2weekend$steps, by=list(interval=d2weekend$interval), mean, na.rm=TRUE)

ad4<-aggregate(steps~interval, d2week, mean, na.rm=TRUE)
ad5<-aggregate(steps~ interval, d2weekend,mean, na.rm=TRUE)

par(mfrow=c(2,1))
plot(ad4, main="Weekdays", 
  xlab="Interval", ylab="No. of steps",type="l",ylim=c(0,250))
plot(ad5, main="Weekends", 
  xlab="Interval", ylab="No. of steps",type="l",ylim=c(0,250))

```
